fixtures:
  repositories:
#    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  forge_modules:
    transition: "puppetlabs/transition"
    facter_cacheable: "waveclaw/facter_cacheable"
    boolean: "puppet/boolean"
  symlinks:
    subscription_manager: "#{source_dir}"
