---
HOSTS:
  centos-7-x64:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vagrant
    box: puppetlabs/centos-7.2-64-nocm
    box_url: https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.2-64-nocm
CONFIG:
  log_level: verbose
  type: foss
